"""Generate the appaaz; Campus CC0 audio sample pack (synthesized in-repo).

All files are original, generated by this script with numpy. No third-party
samples, so they are safe to ship (recorded in ASSETS.md as generated CC0).
Output: mono 16-bit WAV, 44100 Hz, into public/audio/.
"""
import numpy as np
import wave
import os

SR = 44100
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "public", "audio")
os.makedirs(OUT, exist_ok=True)
rng = np.random.default_rng(20260922)


def save(name, x, peak=0.89):
    x = np.asarray(x, dtype=np.float64)
    m = np.abs(x).max()
    if m > 1e-9:
        x = x / m * peak
    pcm = (np.clip(x, -1, 1) * 32767).astype(np.int16)
    with wave.open(os.path.join(OUT, name), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())
    print(f"{name} {len(x) / SR:.2f}s {(len(x) * 2) / 1024:.0f}KB")


def secs(s):
    return int(s * SR)


def brown(n, r=rng):
    """Brown-ish noise via 1/f spectrum shaping (fast, FFT)."""
    w = r.standard_normal(n)
    F = np.fft.rfft(w)
    freqs = np.fft.rfftfreq(n, 1.0 / SR)
    F = F / (freqs + 30.0)
    return np.fft.irfft(F, n)


def white(n, r=rng):
    return r.standard_normal(n)


def lowpass_fft(x, cutoff, order=3):
    """Smooth low-pass (no RNG): rolls off everything above cutoff."""
    n = len(x)
    F = np.fft.rfft(x)
    freqs = np.fft.rfftfreq(n, 1.0 / SR)
    H = 1.0 / (1.0 + (freqs / cutoff) ** (2 * order))
    return np.fft.irfft(F * H, n)


def wash(n, cutoff, r=rng):
    """Airy noise wash with no harsh top end (one RNG draw, like white)."""
    return lowpass_fft(white(n, r), cutoff)


def slow_mod(n, rate_hz=0.08, lo=0.0, hi=1.0, r=rng):
    """Smooth random LFO in [lo, hi] (interpolated coarse noise)."""
    m = max(3, int(n / SR * rate_hz) + 2)
    vals = r.uniform(-1, 1, m)
    t = np.linspace(0, 1, n)
    tc = np.linspace(0, 1, m)
    v = np.interp(t, tc, vals)
    v = 0.5 + 0.5 * v / max(1e-9, np.abs(v).max())
    return lo + (hi - lo) * v


def make_loop(render, dur, xf=1.0):
    """Render dur+xf seconds, fold the tail into the head for a seamless loop."""
    M = secs(xf)
    N = secs(dur)
    x = render(N + M)
    t = np.linspace(0, 1, M)
    y = x[:N].copy()
    y[:M] = y[:M] * t + x[N:N + M] * (1 - t)
    return y


def edge(x, ms=4.0):
    """De-click one-shots with short raised-cosine edges."""
    k = max(2, secs(ms / 1000.0))
    w = 0.5 - 0.5 * np.cos(np.linspace(0, np.pi, k))
    x = x.copy()
    x[:k] *= w
    x[-k:] *= w[::-1]
    return x


def tone(freq, dur, harmonics=(1.0, 0.0, 0.0), attack=0.005, decay=None):
    n = secs(dur)
    t = np.arange(n) / SR
    x = np.zeros(n)
    for i, h in enumerate(harmonics):
        if h:
            x += h * np.sin(2 * np.pi * freq * (i + 1) * t)
    a = min(n, max(2, secs(attack)))
    x[:a] *= np.linspace(0, 1, a)
    d = decay or dur
    x *= np.exp(-np.arange(n) / SR / (d / 4.0))
    return x


def sweep(f0, f1, dur, harmonics=(1.0, 0.0)):
    n = secs(dur)
    f = np.linspace(f0, f1, n)
    ph = 2 * np.pi * np.cumsum(f) / SR
    x = np.zeros(n)
    for i, h in enumerate(harmonics):
        if h:
            x += h * np.sin(ph * (i + 1))
    x *= np.sin(np.pi * np.linspace(0, 1, n)) ** 0.7
    return x


# ---------------- ambience loops ----------------
def r_sea(n):
    t = np.arange(n) / SR
    swell = 0.55 + 0.45 * np.sin(2 * np.pi * t / 6.5 + 1.0)
    swell *= 0.65 + 0.35 * slow_mod(n, 0.05)
    return (brown(n) * 0.9 + wash(n, 900) * 0.55) * swell


def r_lagoon(n):
    t = np.arange(n) / SR
    lap = (0.5 + 0.5 * np.sin(2 * np.pi * t / 3.1)) ** 2
    lap = 0.35 + 0.65 * lap
    return (brown(n) * 0.65 + wash(n, 700) * 0.3) * lap


def r_meadow(n):
    gust = 0.4 + 0.6 * slow_mod(n, 0.07)
    return (brown(n) * 0.8 + wash(n, 500) * 0.2) * gust


def r_ridge(n):
    t = np.arange(n) / SR
    gust = 0.5 + 0.5 * slow_mod(n, 0.16)
    whistle_f = 750 + 350 * slow_mod(n, 0.3, -1, 1)
    whistle = 0.04 * np.sin(2 * np.pi * np.cumsum(whistle_f) / SR)
    return (brown(n) * 0.7 + wash(n, 1500) * 0.5) * gust + whistle


def r_plaza(n):
    gust = 0.45 + 0.55 * slow_mod(n, 0.09)
    base = (brown(n) * 0.55 + wash(n, 600) * 0.15) * gust
    # faint distant life: soft high shimmer swells, no voices
    shimmer = 0.02 * slow_mod(n, 0.11) * np.sin(2 * np.pi * 2400 * np.arange(n) / SR)
    return base + shimmer


def chirp(t0, f0, f1, dur, n, amp=0.5, syllables=3):
    x = np.zeros(n)
    start = int(t0 * SR)
    per = secs(dur) // syllables
    for s in range(syllables):
        i0 = start + s * per
        i1 = min(n, i0 + int(per * 0.8))
        if i0 >= n:
            break
        k = i1 - i0
        f = np.linspace(f0, f1, k)
        ph = 2 * np.pi * np.cumsum(f) / SR
        env = np.sin(np.pi * np.linspace(0, 1, k)) ** 1.5
        x[i0:i1] += amp * np.sin(ph) * env
    return x


def r_birds(n):
    local = np.random.default_rng(4451)  # own stream: tuning birds never shifts other samples
    bed = (brown(n, local) * 0.8 + wash(n, 500, local) * 0.2) * (0.4 + 0.6 * slow_mod(n, 0.07, r=local)) * 0.35
    total = bed
    # sparse by design: 3 call clusters per 24 s loop, ~8 s of silence between
    spots = [(2.0, 2600, 3300), (10.5, 3000, 2400), (18.0, 2500, 3200)]
    for t0, f0, f1 in spots:
        total += chirp(t0, f0, f1, 0.28, n, amp=0.32,
                       syllables=int(local.integers(2, 4)))
    # replicate the old 12 s loop's shared-stream draws so later files stay bit-identical
    _n0 = secs(13)
    rng.standard_normal(_n0); rng.standard_normal(_n0)
    rng.uniform(-1, 1, 3)
    for _ in range(8):
        rng.integers(2, 5)
    return total


NOTES = {"A4": 440.0, "C5": 523.25, "D5": 587.33, "E5": 659.25,
         "G5": 783.99, "A5": 880.0, "B5": 987.77, "C6": 1046.5,
         "E6": 1318.5, "A2": 110.0, "E3": 164.81, "A3": 220.0,
         "C4": 261.63, "D4": 293.66, "E4": 329.63, "G4": 392.0}


def r_bgm(n):
    t = np.arange(n) / SR
    x = (0.05 * np.sin(2 * np.pi * NOTES["A2"] * t)
         + 0.04 * np.sin(2 * np.pi * NOTES["E3"] * t)
         + 0.035 * np.sin(2 * np.pi * NOTES["A3"] * t))
    pattern = ["A4", "C5", "D5", "E5", "G5", "E5", "D5", "C5"]
    step = n // len(pattern)
    for i, name in enumerate(pattern):
        nn = tone(NOTES[name], 2.2, harmonics=(1.0, 0.25, 0.08),
                  attack=0.35, decay=1.6)
        i0 = i * step
        i1 = min(n, i0 + len(nn))
        x[i0:i1] += 0.30 * nn[:i1 - i0]
    return x


save("amb-sea.wav", make_loop(r_sea, 10))
save("amb-lagoon.wav", make_loop(r_lagoon, 8))
save("amb-meadow.wav", make_loop(r_meadow, 10))
save("amb-ridge.wav", make_loop(r_ridge, 8))
save("amb-plaza.wav", make_loop(r_plaza, 9))
save("amb-birds.wav", make_loop(r_birds, 24))
save("bgm-calm.wav", make_loop(r_bgm, 16, xf=1.5))

# ---------------- footsteps ----------------
SURF = {
    "grass": dict(n=0.22, kind="grass"),
    "sand": dict(n=0.26, kind="sand"),
    "stone": dict(n=0.16, kind="stone"),
    "wood": dict(n=0.20, kind="wood"),
}


def footstep(kind, variant):
    if kind == "grass":
        dur, n = 0.22, secs(0.22)
        t = np.arange(n) / SR
        x = (brown(n) * (1.0 - 0.15 * variant)
             * np.exp(-t * (17 + 3 * variant))
             + white(n) * 0.15 * np.exp(-t * 30)
             + 0.5 * np.sin(2 * np.pi * (95 - 8 * variant) * t) * np.exp(-t * 22))
    elif kind == "sand":
        dur, n = 0.26, secs(0.26)
        t = np.arange(n) / SR
        x = (white(n) * 0.8 * np.exp(-t * (13 + 2 * variant))
             + brown(n) * 0.3 * np.exp(-t * 14))
    elif kind == "stone":
        dur, n = 0.16, secs(0.16)
        t = np.arange(n) / SR
        f = 720 + 90 * variant
        x = (white(n) * 0.85 * np.exp(-t * 42)
             + 0.4 * np.sin(2 * np.pi * f * t) * np.exp(-t * 36))
    else:  # wood
        dur, n = 0.20, secs(0.20)
        t = np.arange(n) / SR
        f = 168 + 12 * variant
        x = (0.8 * np.sin(2 * np.pi * f * t) * np.exp(-t * 20)
             + 0.4 * np.sin(2 * np.pi * 2 * f * t) * np.exp(-t * 26)
             + white(n) * 0.28 * np.exp(-t * 48))
    return edge(x)


for surf in ("grass", "sand", "stone", "wood"):
    for v in (1, 2):
        save(f"step-{surf}-{v}.wav", footstep(surf, v - 1), peak=0.8)


# ---------------- jetpack + landing ----------------
def r_jet(n):
    t = np.arange(n) / SR
    flutter = 1 + 0.09 * np.sin(2 * np.pi * 9 * t) + 0.05 * (slow_mod(n, 0.4) - 0.5)
    sub = 0.30 * np.sin(2 * np.pi * 52 * t)
    return (brown(n) * 0.95 + white(n) * 0.22) * flutter + sub


save("jetpack-loop.wav", make_loop(r_jet, 2.5, xf=0.4))

n = secs(0.4)
t = np.arange(n) / SR
save("land-thump.wav",
     edge(0.9 * np.sin(2 * np.pi * 55 * t) * np.exp(-t * 10)
          + brown(n) * 0.5 * np.exp(-t * 16)), peak=0.85)

# ---------------- UI + discovery one-shots ----------------
save("ui-click.wav", edge(tone(660, 0.09, (1.0, 0.3))), peak=0.6)
save("toast-pop.wav", edge(sweep(350, 760, 0.14)), peak=0.65)

n1 = tone(NOTES["C5"], 0.35, (1.0, 0.2), attack=0.01, decay=0.3)
n2 = tone(NOTES["G5"], 0.4, (1.0, 0.2), attack=0.01, decay=0.35)
po = np.zeros(max(len(n1), secs(0.12) + len(n2)))
po[:len(n1)] += 0.6 * n1
po[secs(0.12):secs(0.12) + len(n2)] += 0.6 * n2
save("panel-open.wav", edge(po), peak=0.7)

disc = np.zeros(secs(1.0))
for i, name in enumerate(["E5", "G5", "B5", "E6"]):
    nn = tone(NOTES[name], 0.6, (1.0, 0.25, 0.08), attack=0.01, decay=0.5)
    i0 = int(i * 0.13 * SR)
    disc[i0:i0 + len(nn)] += 0.5 * nn[:len(disc) - i0]
save("discovery-chime.wav", edge(disc), peak=0.75)

unl = sweep(500, 1300, 0.5) * 0.7
tail = tone(1568, 0.4, (1.0, 0.2), attack=0.01, decay=0.35) * 0.5
u = np.zeros(max(len(unl), secs(0.3) + len(tail)))
u[:len(unl)] += unl
u[secs(0.3):secs(0.3) + len(tail)] += tail
save("waypoint-unlock.wav", edge(u), peak=0.7)

fan = np.zeros(secs(1.4))
for i, name in enumerate(["C5", "E5", "G5", "C6"]):
    nn = tone(NOTES[name], 0.5, (1.0, 0.3, 0.1), attack=0.01, decay=0.4)
    i0 = int(i * 0.2 * SR)
    fan[i0:i0 + len(nn)] += 0.55 * nn[:len(fan) - i0]
chord = sum(tone(NOTES[k], 0.8, (1.0, 0.25), attack=0.02, decay=0.7)
            for k in ("C5", "E5", "G5")) * 0.3
i0 = secs(0.8)
fan[i0:i0 + len(chord)] += chord[:len(fan) - i0]
save("success-fanfare.wav", edge(fan), peak=0.75)

save("error-soft.wav", edge(sweep(196, 147, 0.3, (1.0, 0.3))), peak=0.6)

pet = sweep(900, 1500, 0.11) * 0.8
pet2 = sweep(1500, 1100, 0.11) * 0.8
pp = np.zeros(len(pet) + len(pet2))
pp[:len(pet)] += pet
pp[len(pet):] += pet2
save("pet-chirp.wav", edge(pp), peak=0.65)

print("done.")
